export const AIRPORTS = [
  { city: "New Delhi", name: "Indira Gandhi International Airport", iata: "DEL", country: "India" },
  { city: "Mumbai", name: "Chhatrapati Shivaji Maharaj International Airport", iata: "BOM", country: "India" },
  { city: "Bangalore", name: "Kempegowda International Airport", iata: "BLR", country: "India" },
  { city: "Chennai", name: "Chennai International Airport", iata: "MAA", country: "India" },
  { city: "Hyderabad", name: "Rajiv Gandhi International Airport", iata: "HYD", country: "India" },
  { city: "Kolkata", name: "Netaji Subhash Chandra Bose International Airport", iata: "CCU", country: "India" },
  { city: "Dubai", name: "Dubai International Airport", iata: "DXB", country: "UAE" },
  { city: "London", name: "Heathrow Airport", iata: "LHR", country: "UK" },
  { city: "London", name: "Gatwick Airport", iata: "LGW", country: "UK" },
  { city: "Paris", name: "Charles de Gaulle Airport", iata: "CDG", country: "France" },
  { city: "Singapore", name: "Changi Airport", iata: "SIN", country: "Singapore" },
  { city: "New York", name: "John F. Kennedy International Airport", iata: "JFK", country: "USA" },
  { city: "New York", name: "Newark Liberty International Airport", iata: "EWR", country: "USA" },
  { city: "Los Angeles", name: "Los Angeles International Airport", iata: "LAX", country: "USA" },
  { city: "San Francisco", name: "San Francisco International Airport", iata: "SFO", country: "USA" },
  { city: "Tokyo", name: "Narita International Airport", iata: "NRT", country: "Japan" },
  { city: "Tokyo", name: "Haneda Airport", iata: "HND", country: "Japan" },
  { city: "Bangkok", name: "Suvarnabhumi Airport", iata: "BKK", country: "Thailand" },
  { city: "Hong Kong", name: "Hong Kong International Airport", iata: "HKG", country: "Hong Kong" },
  { city: "Sydney", name: "Sydney Airport", iata: "SYD", country: "Australia" },
  { city: "Melbourne", name: "Melbourne Airport", iata: "MEL", country: "Australia" },
  { city: "Frankfurt", name: "Frankfurt Airport", iata: "FRA", country: "Germany" },
  { city: "Amsterdam", name: "Amsterdam Airport Schiphol", iata: "AMS", country: "Netherlands" },
  { city: "Rome", name: "Leonardo da Vinci–Fiumicino Airport", iata: "FCO", country: "Italy" },
  { city: "Istanbul", name: "Istanbul Airport", iata: "IST", country: "Turkey" },
  { city: "Doha", name: "Hamad International Airport", iata: "DOH", country: "Qatar" },
  { city: "Abu Dhabi", name: "Abu Dhabi International Airport", iata: "AUH", country: "UAE" },
  { city: "Male", name: "Velana International Airport", iata: "MLE", country: "Maldives" },
  { city: "Colombo", name: "Bandaranaike International Airport", iata: "CMB", country: "Sri Lanka" },
  { city: "Kathmandu", name: "Tribhuvan International Airport", iata: "KTM", country: "Nepal" },
  { city: "Bali", name: "Ngurah Rai International Airport", iata: "DPS", country: "Indonesia" },
  { city: "Phuket", name: "Phuket International Airport", iata: "HKT", country: "Thailand" },
  { city: "Kuala Lumpur", name: "Kuala Lumpur International Airport", iata: "KUL", country: "Malaysia" },
  { city: "Zurich", name: "Zurich Airport", iata: "ZRH", country: "Switzerland" },
  { city: "Madrid", name: "Adolfo Suárez Madrid–Barajas Airport", iata: "MAD", country: "Spain" },
  { city: "Barcelona", name: "Josep Tarradellas Barcelona–El Prat Airport", iata: "BCN", country: "Spain" },
  { city: "Toronto", name: "Toronto Pearson International Airport", iata: "YYZ", country: "Canada" },
  { city: "Vancouver", name: "Vancouver International Airport", iata: "YVR", country: "Canada" },
];
