export const AIRPORTS = [
  // --- INDIA ---
  { city: "New Delhi", name: "Indira Gandhi International Airport", iata: "DEL", country: "India" },
  { city: "Mumbai", name: "Chhatrapati Shivaji Maharaj International Airport", iata: "BOM", country: "India" },
  { city: "Bangalore", name: "Kempegowda International Airport", iata: "BLR", country: "India" },
  { city: "Chennai", name: "Chennai International Airport", iata: "MAA", country: "India" },
  { city: "Hyderabad", name: "Rajiv Gandhi International Airport", iata: "HYD", country: "India" },
  { city: "Kolkata", name: "Netaji Subhash Chandra Bose International Airport", iata: "CCU", country: "India" },
  { city: "Ahmedabad", name: "Sardar Vallabhbhai Patel International Airport", iata: "AMD", country: "India" },
  { city: "Pune", name: "Pune Airport", iata: "PNQ", country: "India" },
  { city: "Goa", name: "Dabolim Airport", iata: "GOI", country: "India" },
  { city: "Goa", name: "Manohar International Airport", iata: "GOX", country: "India" },
  { city: "Jaipur", name: "Jaipur International Airport", iata: "JAI", country: "India" },
  { city: "Lucknow", name: "Chaudhary Charan Singh International Airport", iata: "LKO", country: "India" },
  { city: "Kochi", name: "Cochin International Airport", iata: "COK", country: "India" },
  { city: "Guwahati", name: "Lokpriya Gopinath Bordoloi International Airport", iata: "GAU", country: "India" },
  { city: "Amritsar", name: "Sri Guru Ram Dass Jee International Airport", iata: "ATQ", country: "India" },
  { city: "Srinagar", name: "Srinagar International Airport", iata: "SXR", country: "India" },
  { city: "Chandigarh", name: "Shaheed Bhagat Singh International Airport", iata: "IXC", country: "India" },
  { city: "Bhubaneswar", name: "Biju Patnaik International Airport", iata: "BBI", country: "India" },
  { city: "Indore", name: "Devi Ahilyabai Holkar Airport", iata: "IDR", country: "India" },
  { city: "Varanasi", name: "Lal Bahadur Shastri International Airport", iata: "VNS", country: "India" },
  { city: "Patna", name: "Jay Prakash Narayan Airport", iata: "PAT", country: "India" },
  { city: "Ranchi", name: "Birsa Munda Airport", iata: "IXR", country: "India" },
  { city: "Coimbatore", name: "Coimbatore International Airport", iata: "CJB", country: "India" },
  { city: "Madurai", name: "Madurai Airport", iata: "IXM", country: "India" },
  { city: "Port Blair", name: "Veer Savarkar International Airport", iata: "IXZ", country: "India" },
  { city: "Agra", name: "Agra Airport", iata: "AGR", country: "India" },
  { city: "Udaipur", name: "Maharana Pratap Airport", iata: "UDR", country: "India" },
  { city: "Jodhpur", name: "Jodhpur Airport", iata: "JDH", country: "India" },
  { city: "Shimla", name: "Shimla Airport", iata: "SLV", country: "India" },
  { city: "Dehradun", name: "Jolly Grant Airport", iata: "DED", country: "India" },
  { city: "Surat", name: "Surat International Airport", iata: "STV", country: "India" },

  // --- MIDDLE EAST ---
  { city: "Dubai", name: "Dubai International Airport", iata: "DXB", country: "UAE" },
  { city: "Abu Dhabi", name: "Abu Dhabi International Airport", iata: "AUH", country: "UAE" },
  { city: "Doha", name: "Hamad International Airport", iata: "DOH", country: "Qatar" },
  { city: "Muscat", name: "Muscat International Airport", iata: "MCT", country: "Oman" },
  { city: "Riyadh", name: "King Khalid International Airport", iata: "RUH", country: "Saudi Arabia" },
  { city: "Jeddah", name: "King Abdulaziz International Airport", iata: "JED", country: "Saudi Arabia" },
  { city: "Kuwait City", name: "Kuwait International Airport", iata: "KWI", country: "Kuwait" },
  { city: "Bahrain", name: "Bahrain International Airport", iata: "BAH", country: "Bahrain" },

  // --- ASIA PACIFIC ---
  { city: "Singapore", name: "Changi Airport", iata: "SIN", country: "Singapore" },
  { city: "Bangkok", name: "Suvarnabhumi Airport", iata: "BKK", country: "Thailand" },
  { city: "Phuket", name: "Phuket International Airport", iata: "HKT", country: "Thailand" },
  { city: "Krabi", name: "Krabi International Airport", iata: "KBV", country: "Thailand" },
  { city: "Kuala Lumpur", name: "Kuala Lumpur International Airport", iata: "KUL", country: "Malaysia" },
  { city: "Bali", name: "Ngurah Rai International Airport", iata: "DPS", country: "Indonesia" },
  { city: "Jakarta", name: "Soekarno–Hatta International Airport", iata: "CGK", country: "Indonesia" },
  { city: "Tokyo", name: "Narita International Airport", iata: "NRT", country: "Japan" },
  { city: "Tokyo", name: "Haneda Airport", iata: "HND", country: "Japan" },
  { city: "Osaka", name: "Kansai International Airport", iata: "KIX", country: "Japan" },
  { city: "Seoul", name: "Incheon International Airport", iata: "ICN", country: "South Korea" },
  { city: "Hong Kong", name: "Hong Kong International Airport", iata: "HKG", country: "Hong Kong" },
  { city: "Sydney", name: "Sydney Airport", iata: "SYD", country: "Australia" },
  { city: "Melbourne", name: "Melbourne Airport", iata: "MEL", country: "Australia" },
  { city: "Perth", name: "Perth Airport", iata: "PER", country: "Australia" },
  { city: "Auckland", name: "Auckland Airport", iata: "AKL", country: "New Zealand" },
  { city: "Male", name: "Velana International Airport", iata: "MLE", country: "Maldives" },
  { city: "Colombo", name: "Bandaranaike International Airport", iata: "CMB", country: "Sri Lanka" },
  { city: "Kathmandu", name: "Tribhuvan International Airport", iata: "KTM", country: "Nepal" },
  { city: "Ho Chi Minh City", name: "Tan Son Nhat International Airport", iata: "SGN", country: "Vietnam" },
  { city: "Hanoi", name: "Noi Bai International Airport", iata: "HAN", country: "Vietnam" },
  { city: "Manila", name: "Ninoy Aquino International Airport", iata: "MNL", country: "Philippines" },

  // --- EUROPE ---
  { city: "London", name: "Heathrow Airport", iata: "LHR", country: "UK" },
  { city: "London", name: "Gatwick Airport", iata: "LGW", country: "UK" },
  { city: "Paris", name: "Charles de Gaulle Airport", iata: "CDG", country: "France" },
  { city: "Frankfurt", name: "Frankfurt Airport", iata: "FRA", country: "Germany" },
  { city: "Munich", name: "Munich Airport", iata: "MUC", country: "Germany" },
  { city: "Amsterdam", name: "Amsterdam Airport Schiphol", iata: "AMS", country: "Netherlands" },
  { city: "Zurich", name: "Zurich Airport", iata: "ZRH", country: "Switzerland" },
  { city: "Rome", name: "Leonardo da Vinci–Fiumicino Airport", iata: "FCO", country: "Italy" },
  { city: "Milan", name: "Malpensa Airport", iata: "MXP", country: "Italy" },
  { city: "Madrid", name: "Adolfo Suárez Madrid–Barajas Airport", iata: "MAD", country: "Spain" },
  { city: "Barcelona", name: "Josep Tarradellas Barcelona–El Prat Airport", iata: "BCN", country: "Spain" },
  { city: "Istanbul", name: "Istanbul Airport", iata: "IST", country: "Turkey" },
  { city: "Vienna", name: "Vienna International Airport", iata: "VIE", country: "Austria" },
  { city: "Prague", name: "Václav Havel Airport Prague", iata: "PRG", country: "Czech Republic" },
  { city: "Athens", name: "Athens International Airport", iata: "ATH", country: "Greece" },
  { city: "Santorini", name: "Santorini (Thira) International Airport", iata: "JTR", country: "Greece" },
  { city: "Mykonos", name: "Mykonos International Airport", iata: "JMK", country: "Greece" },

  // --- AMERICAS ---
  { city: "New York", name: "John F. Kennedy International Airport", iata: "JFK", country: "USA" },
  { city: "New York", name: "Newark Liberty International Airport", iata: "EWR", country: "USA" },
  { city: "Los Angeles", name: "Los Angeles International Airport", iata: "LAX", country: "USA" },
  { city: "San Francisco", name: "San Francisco International Airport", iata: "SFO", country: "USA" },
  { city: "Chicago", name: "O'Hare International Airport", iata: "ORD", country: "USA" },
  { city: "Miami", name: "Miami International Airport", iata: "MIA", country: "USA" },
  { city: "Toronto", name: "Toronto Pearson International Airport", iata: "YYZ", country: "Canada" },
  { city: "Vancouver", name: "Vancouver International Airport", iata: "YVR", country: "Canada" },
];
