export const COUNTRIES = [
  { name: "India", code: "+91", flag: "🇮🇳" },
  { name: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { name: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { name: "United States", code: "+1", flag: "🇺🇸" },
  { name: "Singapore", code: "+65", flag: "🇸🇬" },
  { name: "Australia", code: "+61", flag: "🇦🇺" },
  { name: "Canada", code: "+1", flag: "🇨🇦" },
  { name: "France", code: "+33", flag: "🇫🇷" },
  { name: "Germany", code: "+49", flag: "🇩🇪" },
  { name: "Japan", code: "+81", flag: "🇯🇵" },
  { name: "Thailand", code: "+66", flag: "🇹🇭" },
  { name: "Malaysia", code: "+60", flag: "🇲🇾" },
  { name: "Indonesia", code: "+62", flag: "🇮🇩" },
  { name: "Maldives", code: "+960", flag: "🇲🇻" },
  { name: "Sri Lanka", code: "+94", flag: "🇱🇰" },
  { name: "Nepal", code: "+977", flag: "🇳🇵" },
  { name: "Qatar", code: "+974", flag: "🇶🇦" },
  { name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { name: "Oman", code: "+968", flag: "🇴🇲" },
  { name: "Kuwait", code: "+965", flag: "🇰🇼" },
  { name: "Bahrain", code: "+973", flag: "🇧🇭" },
  { name: "Switzerland", code: "+41", flag: "🇨🇭" },
  { name: "Italy", code: "+39", flag: "🇮🇹" },
  { name: "Spain", code: "+34", flag: "🇪🇸" },
  { name: "Netherlands", code: "+31", flag: "🇳🇱" },
  { name: "Turkey", code: "+90", flag: "🇹🇷" },
  { name: "South Africa", code: "+27", flag: "🇿🇦" },
  { name: "New Zealand", code: "+64", flag: "🇳🇿" },
  { name: "Hong Kong", code: "+852", flag: "🇭🇰" },
  { name: "Vietnam", code: "+84", flag: "🇻🇳" },
  { name: "Philippines", code: "+63", flag: "🇵🇭" },
].sort((a, b) => a.name.localeCompare(b.name));
