import type { Package } from "./packages";

export const SEED_PACKAGES: Package[] = [
  {
    id: "seed-bali-01",
    slug: "bali-luxury-escape",
    title: "Bali Luxury Escape",
    destination: "Bali, Indonesia",
    duration_days: 7,
    price_inr: 45000,
    original_price_inr: 65000,
    category: "Honeymoon",
    is_active: true,
    max_pax: 8,
    created_at: "2026-01-01",
    images: ["https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80"],
    inclusions: [
      "Return flights from Delhi/Mumbai",
      "6 nights in 5★ private villa",
      "Daily breakfast + 2 dinners",
      "Airport transfers",
      "Uluwatu sunset tour",
      "Ubud rice-terrace walk",
    ],
    exclusions: ["Visa fee (~₹2,000)", "Personal expenses", "Lunch"],
    itinerary: [
      { day: 1, title: "Arrival in Bali", activities: ["Airport pickup", "Check-in at villa", "Welcome dinner at beach restaurant"] },
      { day: 2, title: "Ubud Exploration", activities: ["Tegalalang rice terraces", "Monkey Forest", "Traditional cooking class"] },
      { day: 3, title: "Uluwatu & Sunset", activities: ["Uluwatu cliff temple", "Kecak fire dance", "Seafood BBQ at Jimbaran"] },
      { day: 4, title: "Beach & Water Sports", activities: ["Seminyak beach", "Surfing lesson", "Sunset cocktails"] },
      { day: 5, title: "Spa & Wellness", activities: ["Traditional Balinese massage", "Yoga session", "Free evening"] },
      { day: 6, title: "Day Trip to Nusa Penida", activities: ["Kelingking Beach", "Angel's Billabong", "Crystal Bay snorkeling"] },
      { day: 7, title: "Departure", activities: ["Morning at leisure", "Airport drop-off"] },
    ],
  },
  {
    id: "seed-maldives-01",
    slug: "maldives-overwater-villa",
    title: "Maldives Overwater Villa",
    destination: "Maldives",
    duration_days: 6,
    price_inr: 120000,
    original_price_inr: 160000,
    category: "Luxury",
    is_active: true,
    max_pax: 4,
    created_at: "2026-01-01",
    images: ["https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80"],
    inclusions: [
      "Return flights from Delhi/Mumbai",
      "Seaplane transfers",
      "5 nights overwater bungalow",
      "All-inclusive meals",
      "Snorkeling equipment",
      "Sunset dolphin cruise",
    ],
    exclusions: ["Spa treatments", "Personal expenses", "Dive certification"],
    itinerary: [
      { day: 1, title: "Arrival & Seaplane Transfer", activities: ["Arrival at Malé airport", "Scenic seaplane to resort", "Check-in, sundowners"] },
      { day: 2, title: "Ocean & Reef", activities: ["House reef snorkeling", "Glass-bottom boat tour", "Romantic beach dinner"] },
      { day: 3, title: "Water Activities", activities: ["Windsurfing lesson", "Stand-up paddleboarding", "Dolphin cruise"] },
      { day: 4, title: "Island Hopping", activities: ["Local island visit", "Sandbank picnic", "Stargazing"] },
      { day: 5, title: "Relaxation Day", activities: ["Over-water hammock", "Snorkeling at coral garden", "Spa (optional)"] },
      { day: 6, title: "Departure", activities: ["Final breakfast", "Seaplane transfer", "Flight home"] },
    ],
  },
  {
    id: "seed-europe-01",
    slug: "europe-grand-tour",
    title: "Europe Grand Tour",
    destination: "Paris · Rome · Amsterdam",
    duration_days: 11,
    price_inr: 185000,
    original_price_inr: 230000,
    category: "Heritage",
    is_active: true,
    max_pax: 12,
    created_at: "2026-01-01",
    images: ["https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80"],
    inclusions: [
      "Return flights",
      "Schengen visa assistance",
      "10 nights 4★ hotels",
      "Eurostar + Intercity trains",
      "Daily breakfast",
      "Guided city tours",
    ],
    exclusions: ["Lunch & dinner", "Personal expenses", "Optional excursions"],
    itinerary: [
      { day: 1, title: "Fly to Paris", activities: ["Arrival", "Evening at Champs-Élysées"] },
      { day: 2, title: "Paris Classics", activities: ["Eiffel Tower", "Louvre Museum", "Seine river cruise"] },
      { day: 3, title: "Versailles Day Trip", activities: ["Palace of Versailles", "Gardens walk", "Back to Paris"] },
      { day: 4, title: "Paris → Rome by Air", activities: ["Morning flight", "Colosseum visit", "Trastevere dinner"] },
      { day: 5, title: "Rome Highlights", activities: ["Vatican Museums", "Sistine Chapel", "Roman Forum"] },
      { day: 6, title: "Rome Free Day", activities: ["Spanish Steps", "Trevi Fountain", "Shopping"] },
      { day: 7, title: "Rome → Amsterdam", activities: ["Morning flight", "Canal boat tour"] },
      { day: 8, title: "Amsterdam Highlights", activities: ["Anne Frank House", "Rijksmuseum", "Vondelpark"] },
      { day: 9, title: "Tulip Fields & Windmills", activities: ["Keukenhof Gardens", "Zaanse Schans windmills"] },
      { day: 10, title: "Amsterdam Leisure", activities: ["Diamond factory", "Heineken Experience", "Free evening"] },
      { day: 11, title: "Departure", activities: ["Transfer to airport", "Fly home"] },
    ],
  },
  {
    id: "seed-dubai-01",
    slug: "dubai-extravaganza",
    title: "Dubai Extravaganza",
    destination: "Dubai, UAE",
    duration_days: 6,
    price_inr: 60000,
    original_price_inr: 80000,
    category: "Adventure",
    is_active: true,
    max_pax: 10,
    created_at: "2026-01-01",
    images: ["https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80"],
    inclusions: [
      "Return flights",
      "Visa assistance",
      "5 nights 5★ hotel",
      "Desert safari with BBQ dinner",
      "Burj Khalifa At The Top",
      "Dhow cruise dinner",
    ],
    exclusions: ["Personal shopping", "Optional activities"],
    itinerary: [
      { day: 1, title: "Arrival in Dubai", activities: ["Airport pickup", "Hotel check-in", "Dubai Mall visit"] },
      { day: 2, title: "Modern Dubai", activities: ["Burj Khalifa (At The Top)", "Dubai Fountain show", "JBR Beach"] },
      { day: 3, title: "Desert Safari", activities: ["Dune bashing", "Camel riding", "BBQ dinner with belly dance"] },
      { day: 4, title: "Old Dubai", activities: ["Gold Souk", "Spice Souk", "Dhow Cruise Dinner"] },
      { day: 5, title: "Abu Dhabi Day Trip", activities: ["Sheikh Zayed Grand Mosque", "Corniche", "Ferrari World"] },
      { day: 6, title: "Departure", activities: ["Last-minute shopping", "Airport transfer"] },
    ],
  },
];
